version: "3.8"

services:
  orkes-conductor:
    image: orkesio/orkes-conductor-community-standalone:latest
    init: true
    ports:
      - "8081:8080"
      - "1234:5000"
    volumes:
      - redis-data:/redis
      - postgres:/pgdata

volumes:
  redis-data:
  postgres:
