version: "3"
#NETWORKS
networks:
  my-network:
    driver: bridge
#VOLUMES
volumes:
  dir-site:
    driver_opts:
      # Path to folder store project in your local
      device: C:\DATA\docker
      o: bind
      type: "nfs"
services:
  # container PHP
  my-php:
    container_name: c-php
    build:
      dockerfile: Dockerfile
      context: ./php/
      args: 
        - WITH_XDEBUG=true
    restart: always
    hostname: php
    networks:
      - my-network
    volumes:
      - dir-site:/home/www/
      - ./php/php.ini:/usr/local/etc/php/php.ini
    environment:
      XDEBUG_CONFIG: remote_host=192.168.1.78 remote_port=9001
  my-php56:
    container_name: c-php56
    build:
      dockerfile: Dockerfile
      context: ./php56/
      args: 
        - WITH_XDEBUG=true
    restart: always
    hostname: php
    networks:
      - my-network
    volumes:
      - dir-site:/home/www/
      - ./php56/php.ini:/usr/local/etc/php/php.ini
    environment:
      XDEBUG_CONFIG: remote_host=192.168.1.78 remote_port=9001
  # container HTTPD
  my-httpd:
    container_name: c-httpd
    image: "httpd:latest"
    restart: always
    hostname: httpd
    networks:
      - my-network
    volumes:
      - dir-site:/home/www/
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./httpd/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    ports:
      - "80:80"
      - "443:443"
  # container MySQL
  my-mysql:
    container_name: c-mysql
    image: "mysql:latest"
    restart: always
    networks:
      - my-network
    volumes:
      - ./db:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./databases:/home/databases
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=A@123456789abcd
      - MYSQL_DATABASE=wp_dbtest
      - MYSQL_USER=siteuser
      - MYSQL_PASSWORD=sitepass
    ports:
      - "8083:3306"

      