version: "3"
#NETWORKS
networks:
  my-network:
    driver: bridge
#VOLUMES
volumes:
  dir-site:
    driver_opts:
      # Path to folder store project in your local
      device: C:\DATA\docker
      o: bind
      type: "nfs"
services:
  my-mysql:
    container_name: c-mysql
    image: "mysql:latest"
    restart: always
    networks:
      - my-network
    volumes:
      - ./db:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./databases:/home/databases
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=A@123456789abcd
      - MYSQL_DATABASE=wp_dbtest
      - MYSQL_USER=siteuser
      - MYSQL_PASSWORD=sitepass
    ports:
      - "8083:3306"

  # postgres:
  #   container_name: postgres
  #   image: postgres
  #   restart: always
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   ports:
  #     - "6543:5432"
  #   environment:
  #     - POSTGRES_DB=tigergcp
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=12345678

  # adminer:
  #   container_name: adminer
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
